# Generated by Django 5.1.3 on 2024-12-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('can_manage_parts', models.BooleanField(default=False)),
                ('allowed_part_types', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_type', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('aircraft_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.aircraftmodel')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.team')),
            ],
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_date', models.DateTimeField(auto_now_add=True)),
                ('is_listed', models.BooleanField(default=False)),
                ('aircraft_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.aircraftmodel')),
                ('parts', models.ManyToManyField(to='product.part')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
